-- ==========================================
-- SQL Schema Updates: Orders payment/coupon fields
-- Elforat Pharma
-- ==========================================

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS payment_method TEXT,
  ADD COLUMN IF NOT EXISTS payment_status TEXT,
  ADD COLUMN IF NOT EXISTS merchant_order_id TEXT,
  ADD COLUMN IF NOT EXISTS paymob_order_id TEXT,
  ADD COLUMN IF NOT EXISTS coupon_code TEXT,
  ADD COLUMN IF NOT EXISTS discount_amount NUMERIC DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON orders(payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_merchant_order_id ON orders(merchant_order_id);
CREATE INDEX IF NOT EXISTS idx_orders_coupon_code ON orders(coupon_code);


-- ==========================================
-- Order operations: timeline + Telegram notification monitoring
-- ==========================================

CREATE TABLE IF NOT EXISTS public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  old_status text,
  new_status text not null,
  old_status_code text,
  new_status_code text,
  changed_by text,
  changed_at timestamptz not null default now()
);

CREATE INDEX IF NOT EXISTS idx_order_status_history_order_time
  ON public.order_status_history(order_id, changed_at DESC);

CREATE TABLE IF NOT EXISTS public.order_notification_log (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  event_type text not null default 'INSERT',
  status text not null default 'pending' CHECK (status IN ('pending','sent','failed')),
  attempts integer not null default 0,
  last_error text,
  telegram_message_id bigint,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  updated_at timestamptz not null default now()
);

CREATE INDEX IF NOT EXISTS idx_order_notification_log_order
  ON public.order_notification_log(order_id, created_at DESC);

ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_notification_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS order_status_history_admin_read ON public.order_status_history;
CREATE POLICY order_status_history_admin_read
  ON public.order_status_history FOR SELECT TO authenticated
  USING ((SELECT public.is_admin()));

DROP POLICY IF EXISTS order_notification_log_admin_read ON public.order_notification_log;
CREATE POLICY order_notification_log_admin_read
  ON public.order_notification_log FOR SELECT TO authenticated
  USING ((SELECT public.is_admin()));

-- Realtime is used by the admin order screen for instant timeline/notification updates.
ALTER PUBLICATION supabase_realtime ADD TABLE public.order_status_history;
ALTER PUBLICATION supabase_realtime ADD TABLE public.order_notification_log;
